version: '3.7'
# - https://www.mongodb.com/compatibility/docker
services:
#   mongohealthcheck:
#     image: mongodb/mongodb-community-server:6.0-ubi8
#     env_file: .env
#     environment:
#       # - CONN_STR=mongodb://user:pass@mongodb
#       - CONN_STR=mongodb://${DATAVIZ_POC_MONGO_USER}:${DATAVIZ_POC_MONGO_SECRET}@mongo.dataviz_poc.io:27017/
#     command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
#     depends_on:
#       - mongodb
#     networks:
#       - dataviz_poc_net

  jupyter_deno_aarch64:
    image: decoderleco/deno-jupyter:0.0.1-alpha-aarch64
    build:
      context: ./oci/deno-jupyter-aarch64/
      dockerfile: Dockerfile
      # dockerfile: prod.Dockerfile
      args:
        DATAVIZ_NOTEBOOKS_HOME: /usr/dataviz/notebooks/decoderleco
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $PWD/notebooks:/usr/dataviz/notebooks/decoderleco:rw
      - jupyter_deno_cache:/root/.cache/deno:rw
      - jupyter_r_packages_data:/usr/local/lib/R/site-library:rw
    restart: always
    stdin_open: true 
    tty: true
    environment:
      - DATAVIZ_NOTEBOOKS_HOME=/usr/dataviz/notebooks/decoderleco
    ports:
        - '0.0.0.0:8888:8888'
    networks:
      dataviz_poc_net:
        aliases:
          - api.dataviz_poc.io
          - dataviz_poc.io
    depends_on:
      - mongodb
  jupyter_deno:
    image: decoderleco/deno-jupyter:0.0.1-alpha
    build:
      context: ./oci/deno-jupyter/
      dockerfile: Dockerfile
      # dockerfile: prod.Dockerfile
      args:
        DATAVIZ_NOTEBOOKS_HOME: /usr/dataviz/notebooks/decoderleco
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $PWD/notebooks:/usr/dataviz/notebooks/decoderleco:rw
      - jupyter_deno_cache:/root/.cache/deno:rw
      - jupyter_r_packages_data:/usr/local/lib/R/site-library:rw
    restart: always
    stdin_open: true 
    tty: true
    environment:
      - DATAVIZ_NOTEBOOKS_HOME=/usr/dataviz/notebooks/decoderleco
    ports:
        - '0.0.0.0:8888:8888'
    networks:
      dataviz_poc_net:
        aliases:
          - api.dataviz_poc.io
          - dataviz_poc.io
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dataviz_poc
      - MONGO_INITDB_ROOT_PASSWORD=dataviz_poc
    ports:
      - '0.0.0.0:27017:27017'
      # -
      #  in /C/Windows/System32/drivers/etc/hosts
      # -
      # 192.168.218.202        mongo.dataviz_poc.io
      # -
      #  Then with Mongoose, use the MongoDBURL WITHOUT the 
      #  Root username and password : 
      #      mongodb://mongo.dataviz_poc.io:27017/
      # --- 
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - dataviz_poc_mongo_data:/data/db
    networks:
      dataviz_poc_net:
        aliases:
          - mongo.dataviz_poc.io
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: "decolderleco"
      POSTGRES_USER: "pierre"
      POSTGRES_PASSWORD: "chaillot"
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - dataviz_poc_postgres_data:/var/lib/postgresql/data
    networks:
      dataviz_poc_net:
        aliases:
          - postgres.dataviz_poc.io

volumes:
  dataviz_poc_mongo_data:
  dataviz_poc_postgres_data:
  jupyter_deno_cache:
  jupyter_r_packages_data:
networks:
  dataviz_poc_net:
    driver: bridge









# ------------------
